Appointment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('about/', include('about.urls', namespace='about')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('service/', include('service.urls', namespace='service')),
    path('reserve/', include('reserve.urls', namespace='reserve')),
    path('education/', include('education.urls', namespace='education')),
    path('ordering/', include('ordering.urls', namespace='ordering')),



]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('detail/<int:blog_id>/<slug:blog_slug>/', views.BlogDetailView.as_view(), name='detail'),
]

education/urls.py
from django.urls import path
from . import views

app_name = 'education'
urlpatterns = [
    path('list/', views.EducationListView.as_view(), name='education_list'),
    path('detail/<int:education_id>/<slug:education_slug>/', views.DetailEducationView.as_view(),
         name='education_detail'),
]

ordering/urls.py
from django.urls import path
from . import views

app_name = 'ordering'
urlpatterns = [
    path('cart/', views.OrderingView.as_view(), name='cart'),
    path('add/<int:education_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('remove/<int:education_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('apply/<int:order_id>/', views.ApplyCouponView.as_view(), name='apply_coupon'),
]

education/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Education(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField()
    image = models.ImageField(upload_to='education')
    short_description = models.TextField()
    description = models.TextField()
    price = models.IntegerField()
    offer = models.IntegerField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} - {self.price}'

    def get_absolute_url(self):
        return reverse('education_detail', args=[self.slug])


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    education = models.ForeignKey(Education, on_delete=models.CASCADE, related_name='comment')

education/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

education/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Education
from .forms import CommentForm
from django.contrib import messages
from ordering.forms import CartAddForm


# Create your views here.

class EducationListView(View):
    def get(self, request):
        educations = Education.objects.filter(is_active=True)
        return render(request, 'education/education.html', {'educations': educations})


class DetailEducationView(View):
    form_class = CommentForm
    template_name = 'education/detail.html'

    def setup(self, request, *args, **kwargs):
        self.education_instance = get_object_or_404(Education, pk=kwargs['education_id'], slug=kwargs['education_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = self.education_instance.comment.all()
        form_cart = CartAddForm()
        return render(request, self.template_name, {'details': self.education_instance,
                                                    'comments': comments,
                                                    'form': self.form_class,
                                                    'form_cart': form_cart})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.education = self.education_instance
            new_comment.save()
            messages.success(request, 'your comment is ok!', 'success')
            return redirect('education:education_detail', self.education_instance.id, self.education_instance.slug)
        # return render(request, self.template_name, {'details': self.education_instance,
        #                                             'form': self.form_class})

education/templates/education/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <img src="{{ details.image.url }}" alt="/"> </br>
    {{ details.name }}
    {{ details.description }}
    {{ details.price}}
    {{ details.offer }}
    <form action="{% url 'ordering:cart_add' details.id %}" method="post">
        {% csrf_token %}
        {{ form_cart }}
        <input type="submit" value="Send To Cart">
    </form>
<h3>ثبت نظرات</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
{#        {{ form.name }}#}
{#        {{ form.email}}#}
{#        {{ form.body }}#}
        <input type="submit" value="SEND">
    </form>
    <h3>نظرات</h3>
    {% for comment in comments %}
        {{ comment.name }}
{#        {{ comment.email }}#}
        {{ comment.body }}
    {% empty %}
        <p>هیچ دیدگاهی وجود ندارد</p>
    {% endfor %}

{% endblock %}

education/templates/education/education.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% for education in educations %}
        <img src="{{ education.image.url }}" alt="/"> </br>
        <a href="{% url 'education:education_detail' education.id education.slug %}" >{{ education.name }}</a> </br>
        {{ education.short_description }} </br>
        {{ education.price }} | {{ education.offer }}
    {% endfor %}
{% endblock %}