Appointment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('about/', include('about.urls', namespace='about')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('service/', include('service.urls', namespace='service')),
    path('reserve/', include('reserve.urls', namespace='reserve')),
    path('education/', include('education.urls', namespace='education')),
    path('ordering/', include('ordering.urls', namespace='ordering')),



]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('detail/<int:blog_id>/<slug:blog_slug>/', views.BlogDetailView.as_view(), name='detail'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

reserve/urls.py
from django.urls import path
from . import views

app_name = 'reserve'
urlpatterns = [
    path('typeservice/', views.TypeServiceView.as_view(), name='typeservice'),
    path('reservation/<int:service_id>/', views.ReservationView.as_view(), name='reservation'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tag }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="navbar-brand" active href="{% url 'home:home' %}">صفحه اصلی</a>
            <a class="navbar-brand" active href="{% url 'about:about' %}">درباره ما</a>
            <a class="navbar-brand" active href="{% url 'blog:blog' %}">بلاگ</a>
            <a class="navbar-brand" active href="{% url 'contact:contact' %}">تماس با ما</a>
            <a class="navbar-brand" active href="{% url 'education:education_list' %}">آموزش ها</a>
            <a class="navbar-brand" active href="{% url 'service:service' %}">خدمات</a>
            <a class="navbar-brand" active href="{% url 'reserve:typeservice' %}">رزرو نوبت</a>
            {% if request.user.is_authenticated %}
                <a class="navbar-brand" active href="{% url 'accounts:change_password' %}">نغییر پسورد</a>
                <a class="navbar-brand" active href="{% url 'accounts:user_logout' %}">خروج</a>
            {% else %} 
                 <a class="navbar-brand" active href="{% url 'accounts:user_register' %}">ثبت نام</a>
                 <a class="navbar-brand" active href="{% url 'accounts:user_login' %}">ورود</a>
            {% endif %}
            
        </div>
    </div>
</nav>